import turtle

t = turtle.Turtle()
t.hideturtle()
t.pensize(2)
t.speed(0)

def drawA(t): #Draw Letter A
    t.left(75)
    t.forward(40)
    t.right(150)
    t.forward(40)
    t.penup()
    t.backward(20)
    t.left(70)
    t.pendown()
    t.backward(10)
    t.penup()
    t.home()
def drawB(t): #Draw Letter B
    t.left(90)
    t.forward(40)
    t.right(90)
    for i in range(18):
        t.forward(1.8)
        t.right(10)
    t.left(190)
    for i in range(22):
        t.forward(1.8)
        t.right(10)
    t.penup()    
    t.home()
def drawC(t): #Draw Letter C
    t.left(90)
    t.penup()
    t.forward(20)
    t.pendown()
    for i in range(15):
        t.forward(2.5)
        t.right(9)
    t.penup()
    t.left(225)
    t.forward(26.23)
    t.left(90)
    t.forward(13.36)   
    t.pendown()
    for i in range(15):
        t.forward(2.5)
        t.left(9)
    t.penup()
    t.home()
def drawD(t): #Draw Letter D
    t.left(90)
    t.forward(40)
    t.right(90)
    for i in range(18):
        t.forward(3.4)
        t.right(10)
    t.forward(2)
    t.penup()
    t.home()    
def drawE(t): #Draw Letter E
    t.forward(20)
    t.penup()
    t.backward(20)
    t.left(90)
    t.pendown()
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.penup()
    t.backward(20)
    t.left(90)
    t.pendown()
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.penup()
    t.home()
def drawF(t): #Draw Letter F
    t.left(90)
    t.forward(20)
    t.right(90)
    t.forward(17)
    t.penup()
    t.backward(17)
    t.left(90)
    t.pendown()
    t.forward(20)
    t.right(90)
    t.forward(20)
    t.penup()
    t.home()
def drawG(t): #Draw Letter G
    t.left(90)
    t.penup()
    t.forward(20)
    t.pendown()
    for i in range(15):
        t.forward(2.5)
        t.right(9)
    t.penup()
    t.left(225)
    t.forward(26.23)
    t.left(90)
    t.forward(13.36)   
    t.pendown()
    for i in range(20):
        t.forward(2.5)
        t.left(9)
    t.left(90)
    t.forward(10)
    t.penup()
    t.home()    
def drawH(t): #Draw Letter H
    t.left(90)
    t.forward(40)
    t.penup()
    t.backward(20)
    t.right(90)
    t.pendown()
    t.forward(20)
    t.penup()
    t.left(90)
    t.forward(20)
    t.pendown()
    t.backward(40)
    t.penup()
    t.home()
def drawI(t): #Draw Letter I
    t.forward(20)
    t.penup()
    t.backward(10)
    t.left(90)
    t.pendown()
    t.forward(40)
    t.penup()
    t.left(90)
    t.forward(10)
    t.pendown()
    t.backward(20)
    t.penup()
    t.home()
def drawJ(t): #Draw Letter J
    t.penup()
    t.left(90)
    t.forward(40)
    t.right(90)
    t.pendown()
    t.forward(20)
    t.penup()
    t.backward(10)
    t.right(90)
    t.pendown()
    t.forward(30)
    for i in range(18):
        t.forward(1.4)
        t.right(10)
    t.penup()
    t.home()    
def drawK(t): #Draw Letter K
    t.left(90)
    t.forward(40)
    t.penup()
    t.backward(20)
    t.pendown()
    t.right(45)
    t.forward(28)
    t.penup()
    t.backward(28)
    t.right(90)
    t.pendown()
    t.forward(28)
    t.penup()
    t.home()
def drawL(t): #Draw Letter L
    t.forward(20)
    t.penup()
    t.backward(20)
    t.pendown()
    t.left(90)
    t.forward(40)
    t.penup()
    t.home()
def drawM(t): #Draw Letter M
    t.left(90)
    t.forward(40)
    t.right(135)
    t.forward(20)
    t.left(90)
    t.forward(20)
    t.right(135)
    t.forward(40)
    t.penup()
    t.home()
def drawN(t): #Draw Letter N
    t.left(90)
    t.forward(40)
    t.right(150)
    t.forward(45)
    t.left(150)
    t.forward(40)
    t.penup()
    t.home()
def drawO(t): #Draw Letter O
    t.left(90)
    t.penup()
    t.forward(20)
    t.pendown()
    for i in range(15):
        t.forward(2.5)
        t.right(9)
    for i in range(15):
        t.forward(2.5)
        t.right(9)
    for i in range(10):
        t.forward(2.5)
        t.right(9)
    t.penup()
    t.home()                
def drawP(t): #Draw Letter P
    t.left(90)
    t.forward(40)
    t.right(90)
    for i in range(18):
        t.forward(1.8)
        t.right(10)
    t.penup()
    t.home()
def drawQ(t): #Draw Letter Q
    t.penup()
    t.forward(20)
    t.left(180)
    t.pendown()
    for i in range(15):
        t.forward(2.5)
        t.right(9)
    for i in range(15):
        t.forward(2.5)
        t.right(9)
    for i in range(7):
        t.forward(2.5)
        t.right(9)
    t.right(55)
    t.penup()
    t.forward(10)
    t.pendown()
    t.backward(20)
    t.penup()
    t.forward(10)
    t.left(55)
    t.pendown()
    for i in range(8):
        t.forward(2.5)
        t.right(9)
    t.penup()
    t.home()                  
def drawR(t): #Draw Letter R
    t.left(90)
    t.forward(40)
    t.right(90)
    for i in range(18):
        t.forward(1.8)
        t.right(10)
    t.left(125)
    t.forward(25)
    t.penup()
    t.home()
def drawS(t): #Draw Letter S
    t.left(90)
    t.penup()
    t.forward(10)
    t.right(180)
    t.pendown()
    for i in range(25):
        t.forward(1.8)
        t.left(10)
    t.forward(5)
    for i in range(25):
        t.forward(1.8)
        t.right(10)
    t.penup()
    t.home()
def drawT(t): #Draw Letter T
    t.penup()
    t.forward(20)
    t.left(90)
    t.pendown()
    t.forward(40)
    t.left(90)
    t.penup()
    t.forward(20)
    t.pendown()
    t.backward(40)
    t.penup()
    t.home()        
def drawU(t): #Draw Letter U
    t.left(90)
    t.penup()
    t.forward(40)
    t.pendown()
    t.right(180)
    t.forward(30)
    for i in range (18):
        t.forward(2)
        t.left(10)
    t.forward(30)
    t.penup()
    t.home()
def drawV(t): #Draw Letter V
    t.left(90)
    t.penup()
    t.forward(40)
    t.right(160)
    t.pendown()
    t.forward(40)
    t.left(140)
    t.forward(40)
    t.penup()
    t.home()    
def drawW(t): #Draw Letter W
    t.left(90)
    t.penup()
    t.forward(40)
    t.right(170)
    t.pendown()
    t.forward(40)
    t.left(150)
    t.forward(20)
    t.right(140)
    t.forward(20)
    t.left(150)
    t.forward(40)
    t.penup()
    t.home()
def drawX(t): #Draw Letter X
    t.left(45)
    t.forward(60)
    t.penup()
    t.backward(60)
    t.left(45)
    t.forward(40)
    t.right(135)
    t.pendown()
    t.forward(60)
    t.penup()
    t.home()   
def drawY(t): #Draw Letter Y
    t.penup()
    t.forward(20)
    t.left(90)
    t.pendown()
    t.forward(20)
    t.left(30)
    t.forward(25)
    t.penup()
    t.backward(25)
    t.right(60)
    t.pendown()
    t.forward(25)
    t.penup()
    t.home()
def drawZ(t): #Draw Letter Z
    t.left(90)
    t.penup()
    t.forward(40)
    t.right(90)
    t.pendown()
    t.forward(25)
    t.right(135)
    t.forward(40)
    t.left(135)
    t.forward(25)
    t.penup()
    t.home()
def drawSpace(t): #Draw Space Character (\s)
    t.penup()
    t.forward(40)
    t.home()

def drawAlphabet(t): #Draw All Letters
    drawA(t)
    t.forward(40)
    t.pendown()
    drawB(t)
    t.forward(40*2)
    t.pendown()
    drawC(t)
    t.forward(40*3)
    t.pendown()
    drawD(t)
    t.forward(40*4)
    t.pendown()
    drawE(t)
    t.right(90)
    t.forward(60)
    t.left(90)
    t.pendown()
    drawF(t)
    t.right(90)
    t.forward(60)
    t.left(90)
    t.forward(40)
    t.pendown()
    drawG(t)
    t.right(90)
    t.forward(60)
    t.left(90)
    t.forward(40*2)
    t.pendown()
    drawH(t)
    t.right(90)
    t.forward(60)
    t.left(90)
    t.forward(40*3)
    t.pendown()
    drawI(t)
    t.right(90)
    t.forward(60)
    t.left(90)
    t.forward(40*4)
    t.pendown()
    drawJ(t)
    t.right(90)
    t.forward(120)
    t.left(90)
    t.pendown()
    drawK(t)
    t.right(90)
    t.forward(120)
    t.left(90)
    t.forward(40)
    t.pendown()
    drawL(t)
    t.right(90)
    t.forward(120)
    t.left(90)
    t.forward(40*2)
    t.pendown()
    drawM(t)
    t.right(90)
    t.forward(120)
    t.left(90)
    t.forward(40*3)
    t.pendown()
    drawN(t)
    t.right(90)
    t.forward(120)
    t.left(90)
    t.forward(40*4)
    t.pendown()
    drawO(t)
    t.right(90)
    t.forward(180)
    t.left(90)
    t.pendown()
    drawP(t)
    t.right(90)
    t.forward(180)
    t.left(90)
    t.forward(40)
    t.pendown()
    drawQ(t)
    t.right(90)
    t.forward(180)
    t.left(90)
    t.forward(40*2)
    t.pendown()
    drawR(t)
    t.right(90)
    t.forward(180)
    t.left(90)
    t.forward(40*3)
    t.pendown()
    drawS(t)
    t.right(90)
    t.forward(180)
    t.left(90)
    t.forward(40*4)
    t.pendown()
    drawT(t)
    t.right(90)
    t.forward(240)
    t.left(90)
    t.pendown()
    drawU(t)
    t.right(90)
    t.forward(240)
    t.left(90)
    t.forward(40)
    t.pendown()
    drawV(t)
    t.right(90)
    t.forward(240)
    t.left(90)
    t.forward(40*2)
    t.pendown()
    drawW(t)
    t.right(90)
    t.forward(240)
    t.left(90)
    t.forward(40*3)
    t.pendown()
    drawX(t)
    t.right(90)
    t.forward(240)
    t.left(90)
    t.forward(40*4)
    t.pendown()
    drawY(t)
    t.right(90)
    t.forward(300)
    t.left(90)
    t.forward(40*2)
    t.pendown()
    drawZ(t)
    
name = input("What is your name?")    
def drawName(t, name):
    nameChar = list(name)
    charCount = 1
    for char in nameChar:
        match char:
            case "A" | "a":
                drawA(t)
            case "B" | "b":
                drawB(t)
            case "C" | "c":
                drawC(t)
            case "D" | "d":
                drawD(t)
            case "E" | "e":
                drawE(t)
            case "F" | "f":
                drawF(t)
            case "G" | "g":
                drawG(t)
            case "H" | "h":
                drawH(t)
            case "I" | "i":
                drawI(t)
            case "J" | "j":
                drawJ(t)
            case "K" | "k":
                drawK(t)
            case "L" | "l":
                drawL(t)
            case "M" | "m":
                drawM(t)
            case "N" | "n":
                drawN(t)
            case "O" | "o":
                drawO(t)
            case "P" | "p":
                drawP(t)
            case "Q" | "q":
                drawQ(t)
            case "R" | "r":
                drawR(t)
            case "S" | "s":
                drawS(t)
            case "T" | "t":
                drawT(t)
            case "U" | "u":
                drawU(t)
            case "V" | "v":
                drawV(t)
            case "W" | "w":
                drawW(t)
            case "X" | "x":
                drawX(t)
            case "Y" | "y":
                drawY(t)
            case "Z" | "z":
                drawZ(t)
            case " ":
                drawSpace(t)
        t.forward(40*charCount)
        t.pendown()
        charCount = charCount + 1
t.pendown()
drawName(t, name)   
"""drawAlphabet(t)"""    

   

turtle.done()

